- name: Install AUR helper dependencies
  pacman:
    name: cargo
- name: "Clone AUR helper ({{ aur_helper }})"
  git:
    repo: "https://aur.archlinux.org/{{ aur_helper }}.git"
    dest: "{{ aur_helper_dir }}"
  become: yes
  become_user: "{{ local_user }}"
- name: Build AUR helper
  command:
    chdir: "{{ aur_helper_dir }}"
    cmd: makepkg -s
    creates: "{{ aur_helper_dir }}/pkg"
  become: yes
  become_user: "{{ local_user }}"
- name: Install AUR helper
  command:
    cmd: "sh -c 'pacman -U --noconfirm {{ aur_helper_dir }}/{{ aur_helper }}-*.pkg.tar.zst'"
    creates: "/usr/bin/{{ aur_helper }}"
