- name: Configure timezone
  file:
    src: /usr/share/zoneinfo/Europe/Berlin
    dest: /etc/localtime
    state: link

- name: Configure locale.gen
  blockinfile:
    path: /etc/locale.gen
    insertbefore: BOF
    content: "{{ lookup('file', 'files/locale.gen.block', rstrip=false) }}"
- name: Generate locale
  command:
    cmd: locale-gen
    creates: /usr/lib/locale/locale-archive
- name: Configure locale
  copy:
    dest: /etc/locale.conf
    content: "{{ lookup('file', 'files/locale.conf') }}\n"

- name: Configure pacman options
  blockinfile:
    path: /etc/pacman.conf
    insertafter: '^\[options\]$'
    block: "{{ lookup('file', 'files/pacman.conf.block') }}"
- name: Enable multilib repo
  blockinfile:
    path: /etc/pacman.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK (multilib)"
    insertbefore: '^#\[multilib\]$'
    block: "{{ lookup('file', 'files/pacman.conf-multilib.block') }}"
- name: Use RWTH server for pacman
  copy:
    dest: /etc/pacman.d/mirrorlist
    content: "{{ lookup('file', 'files/mirrorlist') }}\n"
- name: Update system
  pacman:
    update_cache: yes
    upgrade: yes
- name: Install base packages
  pacman:
    name: "{{ lookup('file', 'files/packages.txt').splitlines() | list }}"
- name: Enable rngd service
  systemd:
    name: rngd.service
    enabled: yes

- name: Create local user
  user:
    name: "{{ local_user }}"
    shell: /usr/bin/zsh
    groups: "{{ lookup('file', 'files/groups').splitlines() | list }}"
    append: yes
- name: Allow group wheel to use sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '^(# )?%wheel ALL=\(ALL\) ALL$'
    line: '%wheel ALL=(ALL) ALL'
- include: user.yml
  become: yes
  become_user: "{{ local_user }}"
- include: aur_helper.yml
