# TODO: msmtp
- name: Create base maildir
  file:
    path: "{{ maildir_base_dir }}"
    state: directory
- name: Create personal mutt config
  template:
    src: 'personal.rc.j2'
    dest: "{{ mutt_personal_file }}"
- name: Create parent directory
  file:
    path: "{{ notmuch_config | dirname }}"
    state: directory
- name: Create notmuch config
  template:
    src: 'config.j2'
    dest: "{{ notmuch_config }}"
