- name: Create GPG batch file
  copy:
    dest: "{{ gpg_batch_file }}"
    content: "{{ lookup('template', 'templates/gpg-batch.j2') }}"
- name: Generate GPG key
  command:
    cmd: "gpg --batch --generate-key {{ gpg_batch_file }}"
    creates: '~/.gnupg/private-keys-v1.d'
- name: Create .gitconfig
  copy:
    dest: "~/.gitconfig"
    content: "{{ lookup('template', 'templates/.gitconfig.j2') }}"
- name: Start mutt wizard
  include_tasks: mutt-wizard.yml
  when: mymailaccount is defined
