- name: Create GPG batch file
  template:
    src: 'gpg-batch.j2'
    dest: "{{ gpg_batch_file }}"
- name: Generate GPG key
  command:
    cmd: "gpg --batch --generate-key {{ gpg_batch_file }}"
    creates: '~/.gnupg/private-keys-v1.d'
- name: Create .gitconfig
  template:
    src: '.gitconfig.j2'
    dest: "~/.gitconfig"
- name: Start mutt wizard
  include_tasks: mutt-wizard.yml
  when: mymailaccount is defined
