- name: Interpret hardware clock as UTC
  command:
    cmd: hwclock --systohc
    creates: /etc/adjtime
- name: Configure hostname
  copy:
    dest: /etc/hostname
    content: "{{ myhostname | split(\".\") | first }}\n"
- name: Ensure hosts contains localhost
  blockinfile:
    path: /etc/hosts
    insertafter: '^# See hosts\(5\) for details\.$'
    content: "{{ lookup('template', 'templates/hosts.j2') }}"
