#! /bin/sh

sxhkd &
#compton -b

setxkbmap us -option caps:escape -variant de_se_fi
bspc monitor -d 1 2 3 4

bspc rule -a feh state=floating
bspc rule -a plasmashell state=floating
bspc rule -a latte-dock state=floating border=off
bspc rule -a lattedock state=floating border=off
bspc rule -a Pinentry state=floating
bspc rule -a Steam state=floating

bspc rule -a Zathura state=tiled

bspc config border_width         1
bspc config window_gap           2

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config pointer_action1 resize_corner
bspc config pointer_action2 none
bspc config pointer_action3 move

bspc config presel_feedback_color "#FFFFFF"
bspc config normal_border_color "#78909C"
bspc config focused_border_color "#FF3D00"
bspc config active_border_color "#03A9F4"
