#! /bin/sh

sxhkd &
polybar magnus &
~/Documents/scripts/gen-wallpaper.sh ~/Pictures/Wallpaper/arch_minimalistic.jpg
feh --bg-scale /tmp/wallpaper.png
#compton --config ~/.config/compton/compton.conf -b
#libinput-gestures-setup start

bspc monitor -d Term Web Code Study Chat Music Doc VIII

bspc rule -a feh state=floating
bspc rule -a fluid-demo state=floating

bspc config border_width         6
bspc config window_gap          12

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bsps config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus true

bspc config presel_feedback_color \#FF3D00
bspc config normal_border_color \#78909C
bspc config focused_border_color \#FF3D00
bspc config active_border_color \#03A9F4
