- name: Install productivity packages
  pacman:
    name: "{{ lookup('file', 'files/packages.txt').splitlines() | list }}"
- name: Enable NetworkManager
  systemd:
    name: NetworkManager.service
    enabled: yes
- name: Use iwd as Wifi backend
  copy:
    dest: /etc/NetworkManager/conf.d/wifi_backend.conf
    content: "{{ lookup('file', 'files/wifi_backend.conf') }}\n"
- name: Enable sddm
  systemd:
    name: sddm.service
    enabled: yes
