export XDG_CONFIG_HOME="$HOME/.config"
export LESS='-Ric -x4 --use-color -Dd+r$Du+b'
export MANROFFOPT='-c'
export EDITOR='vim'
export DISABLE_AUTO_UPDATE=true
export DISABLE_MAGIC_FUNCTIONS=true
export TDESKTOP_DISABLE_TRAY_COUNTER=1
export KEYTIMEOUT=1
export FZF_COMPLETION_TRIGGER='~~'
export FZF_DEFAULT_OPTS="--history=$HOME/.cache/.fzf_history"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
export BAT_THEME=ansi
export LDFLAGS="-fuse-ld=mold"
export CMAKE_COLOR_DIAGNOSTICS=ON
export ASAN_OPTIONS='abort_on_error=1'
export QT_FORCE_STDERR_LOGGING=1
export PLASMA_USE_QT_SCALING=1
export QT_USE_PHYSICAL_DPI=1
export MSMTPQ_LOG=~/.cache/mutt/msmtpq/msmtp.queue.log

export LANG=en_US.UTF-8
export LANGUAGE=en_US
export LC_ADDRESS=de_DE.UTF-8
export LC_CTYPE=de_DE.UTF-8
export LC_MEASUREMENT=de_DE.UTF-8
export LC_MONETARY=de_DE.UTF-8
export LC_NAME=de_DE.UTF-8
export LC_NUMERIC=de_DE.UTF-8
export LC_PAPER=de_DE.UTF-8
export LC_TELEPHONE=de_DE.UTF-8
export LC_TIME=de_DE.UTF-8
